Repository Knogueira/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#6 Integrar requisitos v1.0
  docs/requisitos.md
Labels: análise

#9 ISSUE #5
  src/jogovelha.py
Labels: programação

#5 Integrar arquitetura v1.0
  docs/arquitetura.md
Labels: arquitetura

#10 ISSUE #2
  docs/arquitetura.md
Labels: arquitetura

#12 Gerar release v1.0
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: operações

#18 Integrar requisitos v1.1
  docs/requisitos.md
Labels: análise

#17 Integrar arquitetura v1.1
  docs/arquitetura.md
Labels: arquitetura

#19 ISSUE #15
  src/jogovelha.py
Labels: programação

#20 ISSUE #16
  src/testes_inic.py
Labels: testes
